remove metadata
this causes problem while installing from librarian-puupet

```
undefined local variable or method `metadata' for #<Librarian::Puppet::Dsl::Receiver:0x007fe3b2cc6990> (NameError)
```